//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopBrige_API
{
    using System;
    using System.Collections.Generic;
    
    public partial class INVENTORY
    {
        public int INV_ID { get; set; }
        public string INV_CODE { get; set; }
        public string INV_NAME { get; set; }
        public string INV_DESCRIPTION { get; set; }
        public Nullable<decimal> INV_PRICE { get; set; }
        public string INV_STATUS { get; set; }
        public Nullable<int> STOCK_AVB { get; set; }
        public Nullable<bool> DEL_FLAG { get; set; }
        public Nullable<System.DateTime> LST_CHG_DT { get; set; }
    }
}
